# Generated by Django 5.0.6 on 2024-07-09 14:52

import django.db.models.deletion
import vinywaji.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vinywaji_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vinywaji.core.models.uuid_default,
                        help_text="The ID of this webhook",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A free-form description which the user can give this webhook",
                        max_length=128,
                    ),
                ),
                (
                    "transaction_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The description that will be added to the transaction when this webhook is triggered",
                        max_length=30,
                    ),
                ),
                (
                    "trigger_key",
                    models.CharField(
                        default=vinywaji.core.models.webhook_trigger_default,
                        editable=False,
                        help_text="The key required to trigger this webhook",
                        max_length=64,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="How much money the triggered transaction records in euro-cent. Negative amounts represent purchases while positive amounts represent deposits."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        help_text="The user who configured this webhook and who is impacted when it is called",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
