# Generated by Django 3.2.9 on 2021-11-09 11:54

import bitbots_drinks_core.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_auth_mafiasi", "0003_auto_20210204_1525"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "mafiasiauthmodeluser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_auth_mafiasi.mafiasiauthmodeluser",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("django_auth_mafiasi.mafiasiauthmodeluser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=bitbots_drinks_core.models.uuid_default, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(default="", max_length=30)),
                ("amount", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
