# Generated by Django 3.2.9 on 2021-11-11 20:53

import bitbots_drinks_core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bitbots_drinks_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(
                help_text="How much money was involved in this transaction in euro-cent. Negative amounts represent purchases while positive amounts represent deposits."
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(
                default="",
                help_text="Additional free form details a user might wish to add to this transaction",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                default=bitbots_drinks_core.models.uuid_default,
                help_text="The ID of this transaction",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                editable=False,
                help_text="The user with which this transaction is associated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
