# Generated by Django 3.2.9 on 2021-11-11 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitbots_drinks_core", "0002_add_help_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0),
                help_text="When this transaction occurred",
            ),
            preserve_default=False,
        ),
    ]
